add-common-films
alex-from-90/java-filmorate pull request #30
Opened 2023-06-26 15:24 UTC by DayZscripter

2023-06-26 15:29 UTC, DeepDarkFanta approved these changes

2023-06-26 15:29 UTC, DeepDarkFanta commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Request common films of users with id {} and id {}", userId, friendId);
Хорош!

2023-06-26 20:16 UTC, ImING0 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Request common films of users with id {} and id {}", userId, friendId);
Как заметил Алекс в чате ТГ, лучше привести сообщения к единому стилю. В данном кейсе используй русский язык

2023-06-26 20:22 UTC, ImING0 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> commonFilms(@RequestParam Long userId, Long friendId) {
Интересное решение вернуть коллекцию, ведь так мы не привязываемся к конкретной реализации, что позволяет  более гибко менять реализацию коллекций в зависимости от задачи

2023-06-26 20:28 UTC, ImING0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +            throw new NotFoundException("User not " + "found");
Стоит указать, что не найден именно друг пользователя, а не просто пользователь.

2023-06-26 20:35 UTC, ImING0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +        String sql = "SELECT *" + "FROM films AS f "
Лучше каждую  строку запроса начинать с новой строки. Так будет приятнее и удобнее читать запрос. 
Если код стайл переносит строки, напомню об аннотации //@formatter:off

2023-06-26 20:50 UTC, ImING0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +                + "WHERE l1.user_id = ? AND l2.user_id = ? " + "ORDER BY count_like DESC;";
мне кажется, что стоит дать более осмысленное название переменным l1, l2, что думаешь?

2023-06-26 21:04 UTC, ImING0 requested changes
Проверил работу, критических ошибок не обнаружил. Оставил комментарии, с которыми необходимо ознакомиться и внести соотв. изменения

2023-06-26 21:13 UTC, ImING0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +                + "LEFT JOIN (SELECT film_id, COUNT(film_id) AS count_like FROM film_likes GROUP BY film_id) "
Не понял для чего это? В тестах и тз не нашел для этого применения.

2023-06-26 21:52 UTC, DayZscripter commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +                + "WHERE l1.user_id = ? AND l2.user_id = ? " + "ORDER BY count_like DESC;";
согласен, но тогда по всему проекту нужно исправлять подобные переменные, а не только в моем участке кода

2023-06-26 22:07 UTC, ImING0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +                + "WHERE l1.user_id = ? AND l2.user_id = ? " + "ORDER BY count_like DESC;";
> согласен, но тогда по всему проекту нужно исправлять подобные переменные, а не только в моем участке кода

я проверяю конкретно твой участок кода. Думаю, что переменным лучше давать более осмысленные названия:)

2023-06-27 07:15 UTC, ImING0 approved these changes

2023-06-27 07:21 UTC, DayZscripter commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +                + "LEFT JOIN (SELECT film_id, COUNT(film_id) AS count_like FROM film_likes GROUP BY film_id) "
ок,  просто в некоторых реальных сервисах была такая сортировка по лайкам

2023-06-27 07:21 UTC, merged